pipeline {
    agent { label 'slavej' }
    stages {
        stage('Build') {
            steps {
                    git branch: 'master', url: 'https://github.com/1rn09is402/j-repository.git'
                    sh '''
                        #!/bin/bash 
                        pwd 
                        ls
                        echo "This is a BUILD stage"
                        mvn clean package
                    ''' 
            }
        }
    }
}
